version: '3.0'

services:
  nginx:
    image: nginx:1.25.4
    ports:
      - "90:80"
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/node34.webte.fei.stuba.sk/zadanie2
      - $CONFIG_PATH/:/var/www/.config/zadanie2/config.global.php
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/node34.webte.fei.stuba.sk/zadanie2
    volumes:
      - ./:/var/www/node34.webte.fei.stuba.sk/zadanie2
      - $CONFIG_PATH/:/var/www/.config/zadanie2/config.global.php
    depends_on:
      - mysql

  mysql:
    build: ./.docker/mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql 
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:

    mysqldata:
